name: ansible-sign tests
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.8"
          - python: "3.9"
          - python: "3.10"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox

      - name: Let's have some docs!
        run: |
          tox -e docs
          touch docs/_build/html/.nojekyll

      - name: "Deploy 'em 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
